namespace: default
resources:
  - cloudsql
  - beat
  - builder
  - collectstatic
  - migration
  - web
  - worker
  - google-cloud-storage
  - rabbitmq

# TODO: if the issue below ever gets reopened
#    https://github.com/kubernetes-sigs/kustomize/pull/1217
#    then we can get rid of this clause (and the associated file).
configurations:
- kustomizeconfig.yaml

commonLabels:
  app.kubernetes.io/instance: lookit-$SHORT_SHA
  app.kubernetes.io/version: $TAG_NAME
  app.kubernetes.io/part-of: lookit
  app.kubernetes.io/managed-by: kustomize

images:
- name: lookit
  newName: gcr.io/mit-lookit/lookit
  newTag: $COMMIT_SHA

# Configs and secrets
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: lookit-configmap
    files:
      - files_/uwsgi.ini
      - files_/robots.txt

vars:
  - name: CLOUDSQL_INSTANCE_CONNECTION_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: lookit-configmap
    fieldref:
      fieldpath: data.CLOUDSQL_INSTANCE_CONNECTION_NAME
  - name: SITE_DOMAIN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: lookit-configmap
    fieldref:
      fieldpath: data.SITE_DOMAIN
  - name: ENVIRONMENT
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: lookit-configmap
    fieldref:
      fieldpath: data.ENVIRONMENT
  - name: RABBITMQ_HEADLESS_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: lookit-rabbitmq-headless
    fieldref:
      fieldpath: metadata.name
  - name: RABBITMQ_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: lookit-rabbitmq
    fieldref:
      fieldpath: metadata.name

patches:
  - path: patches_/add-cloud-sql-proxy-sidecar.yaml
    target:
      annotationSelector: "cloud-sql-proxy-sidecar=injected"
  - path: patches_/add-lookit-env-vars.yaml
    target:
      annotationSelector: "lookit-env-vars=injected"
  - path: patches_/replace-lookit-env-vars.yaml
    target:
      annotationSelector: "lookit-env-vars=replaced"

