namespace: default
resources:
  - beat
  - builder
  - collectstatic
  - migration
  - web
  - worker
  - google-cloud-storage

# TODO: if the issue below ever gets reopened
#    https://github.com/kubernetes-sigs/kustomize/pull/1217
#    then we can get rid of this clause (and the associated file).
configurations:
- kustomizeconfig.yaml

commonLabels:
  app.kubernetes.io/instance: lookit-617db95
  app.kubernetes.io/version: 0.0.1
  app.kubernetes.io/part-of: lookit
  app.kubernetes.io/managed-by: kustomize

images:
- name: lookit
  newName: gcr.io/mit-lookit/lookit
  newTag: 617db9598c8dd607e43fdd1172b8037c1d86abde

# Configs and secrets
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: lookit-configmap
    files:
      - files_/uwsgi.ini
      - files_/robots.txt

vars:
  - name: CLOUDSQL_INSTANCE_CONNECTION_NAME
    objref:
      kind: ConfigMap
      name: lookit-configmap
      apiVersion: v1
    fieldref:
      fieldpath: data.CLOUDSQL_INSTANCE_CONNECTION_NAME
  - name: SITE_DOMAIN
    objref:
      kind: ConfigMap
      name: lookit-configmap
      apiVersion: v1
    fieldref:
      fieldpath: data.SITE_DOMAIN
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: lookit-configmap
      apiVersion: v1
    fieldref:
      fieldpath: data.ENVIRONMENT

patches:
  - path: patches_/add-cloud-sql-proxy-sidecar.yaml
    target:
      annotationSelector: "cloud-sql-proxy-sidecar=injected"
  - path: patches_/add-lookit-env-vars.yaml
    target:
      annotationSelector: "lookit-env-vars=injected"
  - path: patches_/replace-lookit-env-vars.yaml
    target:
      annotationSelector: "lookit-env-vars=replaced"

