apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
  annotations:
    lookit-env-vars: "injected"
    wait-for-gcloud-sqlproxy: "true"
    wait-for-rabbitmq: "true"
spec:
  selector:
    matchLabels: {}
  template:
    spec:
      initContainers: 
      - name: init-sqlproxy
        image: busybox:1.33
        command:
        - /bin/sh
        args:
        - -c
        - for i in {1..100}; do sleep 1; if dig $(SQLPROXY_SERVICE_NAME); exit 0; fi; exit 1
      containers:
      - name: beat
        image: lookit
        imagePullPolicy: IfNotPresent
        command:
        - gosu
        - www-data
        - celery
        - -A
        - project.celery.app
        - beat
        - -l
        - DEBUG
        - --pidfile=
        env: []
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/googleAppCreds.json
          name: secret-volume
          readOnly: true
          subPath: googleAppCreds.json
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: lookit-configmap
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: lookit-secrets
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
