---
# Source: rabbitmq/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lookit-rabbitmq-endpoint-reader
  labels:
    app: rabbitmq
    chart: rabbitmq-6.15.0
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
