---
# Source: rabbitmq/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lookit-rabbitmq-endpoint-reader
subjects:
- kind: ServiceAccount
  name: lookit-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lookit-rabbitmq-endpoint-reader
