---
# Source: rabbitmq/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lookit-rabbitmq
  labels:
    app: rabbitmq
    chart: rabbitmq-6.15.0
    release: "lookit-rabbitmq"
    heritage: "Helm"
