apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  annotations:
    lookit-env-vars: "injected"
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 5
  template:
    metadata:
      name: migration
    spec:
      containers:
      - name: migration
        image: lookit
        imagePullPolicy: IfNotPresent
        command:
        - python
        - manage.py
        - migrate
        env: []
        volumeMounts:
        - mountPath: /etc/googleAppCreds.json
          name: secret-volume
          readOnly: true
          subPath: googleAppCreds.json
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: lookit-configmap
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: lookit-secrets
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
