apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  annotations:
    cloud-sql-proxy-sidecar: "injected"
    lookit-env-vars: "replaced"
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 6
  completions: 1
  parallelism: 1
  # ttlSecondsAfterFinished here?
  template:
    metadata:
      name: migration
    spec:
      containers:
      - command:
        - python
        - manage.py
        - migrate
        image: lookit
        imagePullPolicy: IfNotPresent
        name: migration
        volumeMounts:
        - mountPath: /etc/googleAppCreds.json
          name: secret-volume
          readOnly: true
          subPath: googleAppCreds.json
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: lookit-configmap
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: lookit-secrets
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
