apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32403
    port: 8080
    protocol: TCP
    targetPort: http
  type: NodePort
