- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: wait-init-rabbitmq
    image: busybox
    command: ["sh", "-c"]
    args: ["until nc -vn rabbitmq:5672; do echo waiting for rabbitmq; sleep 2; done"]