- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: wait-init-gcloud-sqlproxy
    image: bitnami/kubectl:latest
    args: [
      "rollout",
      "status",
      "deployment",
      "-w",
      "$(GCLOUD_SQLPROXY_DEPLOYMENT_NAME)"
    ]