- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: wait-init-rabbitmq
    image: bitnami/kubectl:latest
    args: [
      "rollout",
      "status",
      "statefulset",
      "$(RABBITMQ_STATEFULSET_NAME)"
    ]