- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: wait-init-gcloud-sqlproxy
    image: postgres:9.6
    command:
    - bash
    args: 
    - -c
    - until pg_isready -h $(GCLOUD_SQLPROXY_SERVICE_NAME); do sleep 5; done