- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: wait-init-rabbitmq
    image: busybox:latest
    command: [
      'sh',
      '-c',
      "until nslookup $(RABBITMQ_SERVICE_NAME).$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $(RABBITMQ_SERVICE_NAME); sleep 2; done"
    ]