apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-statefulset-reader
rules:
- apiGroups: ["", "apps", "extensions"]  # "" indicates the core API group
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "watch", "list"]