apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-waiter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-statefulset-reader
subjects:
- kind: ServiceAccount
  name: rollout-waiter