apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-waiter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-statefulset-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: rollout-waiter